---
title: "Artifactual Waves of Aging: iPOP Transcriptomics - Figure 5"
author: "Kate Shutta"
date: "2026-04-10"
output: html_document
---

# Libraries and packages

Load our custom functions for running LOESS+DE-SWAN and investigating simulation results.

```{R}
source("../utils/loess_utils.R")
```

Load libraries.

```{R}
library(DEswan)
library(dplyr)
library(ggplot2)
library(ggpubr)
library(gridExtra)
library(logr)
# optional for parallel processing
library(foreach)
library(doParallel)
```

# Figure 5

Load the sample data. 

```{R}
ipop_sample_data = read.csv("../ipop_data_analysis/nonlinear_aging_data/sample_info.csv")
```

Specify number of simulations and register parallel processing. Note that this is quite time consuming simulation because LOESS must be run on every molecule for every iteration and the span must be optimized. For illustration, we have set `nit=2` and `npred=50` in this notebook. To reproduce the paper, please set `nit=50` and `npred = 8556`.

```{R}
nit = 2
doParallel::registerDoParallel(cores=2)
```

Run LOESS + DE-SWAN on the iPOP age distribution for `nit` different random samples. In each case, the "expression levels" of the 8556 transcripts are simulated independently according to a uniform distribution. 

```{R}
transcriptomic_ipop = foreach(i=1:nit) %dopar%
{ 
  test_age_dist(ipop_sample_data$adjusted_age,
              npred = 50, 
              bucket = 20, 
              optimize_loess = T, 
              do_ipop = T,
              do_log = T,
              distribution = "standard_normal")
}

doParallel::stopImplicitCluster()
```

Plot the waves of aging. Note that you will need to adjust the y-axis depending on the number of predictors you use. To reproduce the results of the paper, please set `ylim(5000,7000)` below.

```{R}
plot_from_sim_list(transcriptomic_ipop,npred=50) + 
  #ylim(5000,7000) +
  ylim(0,50)+
  geom_vline(xintercept = 44, linetype = "dashed") +
  geom_vline(xintercept = 61, linetype = "dashed") +
  annotate("text",x=48.5,y=5000,label="iPOP Tx Crest 1: 44") +
  annotate("text",x=57.5,y=5000,label="iPOP Tx Crest 2: 61") +
  ggtitle('Waves of Aging in Random "Transcriptomics"') +
  theme_minimal() +
  theme(title = element_text(hjust=0.5),
        legend.position = "none")
```


Plot the correlations.

```{R}
npeeps = list()
npeeps[[40]] = sum(ipop_sample_data$adjusted_age >= 40 &
                     ipop_sample_data$adjusted_age < 50 )
for(i in seq(41,65,by=1))
  npeeps[[i]] = sum(ipop_sample_data$adjusted_age >= (i-10) & 
                         ipop_sample_data$adjusted_age < (i + 10))

all_profiles = lapply(transcriptomic_ipop,function(x){get_profile(x[[2]])})
for(i in 1:length(all_profiles))
  all_profiles[[i]]$id = paste0("Trial:",i)

all_profiles_df = Reduce(rbind.data.frame, all_profiles)
mean_profile = all_profiles_df %>%
  group_by(center) %>%
  summarize(mean_nhits = mean(nhits))

mean_profile$npeeps = unlist(npeeps)

library(ggrepel)
ggplot(mean_profile, aes(x=npeeps/nrow(ipop_sample_data), y=mean_nhits, label=center, color=center)) + 
  geom_point() +
  geom_label_repel() + 
  xlab("proportion of total study population falling in sliding window") +
  ylab("average # molecules/8556 with q < 0.05 (nsim = 50)") + 
  ggtitle("Number of hits anticorrelates with number of samples in window")

```